# Generated by Django 4.2.11 on 2026-04-20 01:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('height_min', models.FloatField(blank=True, null=True)),
                ('height_max', models.FloatField(blank=True, null=True)),
                ('weight_min', models.FloatField(blank=True, null=True)),
                ('weight_max', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'db_table': 'pets_breed',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('report_type', models.CharField(choices=[('lost', 'Perdido'), ('found', 'Encontrado')], max_length=10)),
                ('pet_name', models.CharField(help_text='Nombre de la mascota', max_length=100)),
                ('breed_custom', models.CharField(blank=True, help_text='Raza personalizada si no está en la lista', max_length=255)),
                ('color', models.CharField(help_text='Color o características físicas', max_length=100)),
                ('size', models.CharField(choices=[('small', 'Pequeño (0-10 kg)'), ('medium', 'Mediano (10-25 kg)'), ('large', 'Grande (25-50 kg)'), ('giant', 'Gigante (>50 kg)')], max_length=20)),
                ('distinguishing_features', models.TextField(blank=True, help_text='Cicatrices, manchas, collares, etc.')),
                ('collar_name', models.CharField(blank=True, help_text='Nombre en collar (si tiene)', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_description', models.TextField(help_text='Descripción de dónde fue visto/encontrado')),
                ('date_incident', models.DateTimeField(help_text='Fecha y hora del incidente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('resolved', 'Resuelto'), ('archived', 'Archivado')], default='active', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notas sobre cómo se resolvió')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False, help_text='Verificado por administrador')),
                ('priority', models.IntegerField(default=1, help_text='Prioridad para matching (1-10)', validators=[django.core.validators.MinValueValidator(1)])),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.breed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Mascota',
                'verbose_name_plural': 'Reportes de Mascotas',
                'db_table': 'pets_pet_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d/')),
                ('is_verified', models.BooleanField(default=False)),
                ('reputation_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'pets_user_profile',
            },
        ),
        migrations.CreateModel(
            name='PetReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Foto de la mascota', upload_to='pet_reports/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Imagen principal del reporte')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.petreport')),
            ],
            options={
                'verbose_name': 'Imagen de Reporte',
                'verbose_name_plural': 'Imágenes de Reportes',
                'db_table': 'pets_pet_report_image',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Puntuación de similitud (0-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('match_reason', models.TextField(help_text='Razones de la coincidencia')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado'), ('resolved', 'Resuelto')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_found', to='pets.petreport')),
                ('lost_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_lost', to='pets.petreport')),
            ],
            options={
                'verbose_name': 'Coincidencia',
                'verbose_name_plural': 'Coincidencias',
                'db_table': 'pets_match',
                'ordering': ['-match_score'],
            },
        ),
        migrations.AddIndex(
            model_name='petreport',
            index=models.Index(fields=['report_type', 'status'], name='pets_pet_re_report__efe0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='petreport',
            index=models.Index(fields=['latitude', 'longitude'], name='pets_pet_re_latitud_e79919_idx'),
        ),
        migrations.AddIndex(
            model_name='petreport',
            index=models.Index(fields=['user', 'status'], name='pets_pet_re_user_id_78354e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('lost_report', 'found_report')},
        ),
    ]
